### ISSUE TITLE
nuget

### ISSUE THREAD

**Issue by seertenedos** [samuel-lucas6/ChaCha.NET#1]
Any chance of publishing a nuget so it is easy to get the latest instead of needing to put a copy of the code in a project? I have a need for chacha8 and it seems yours is the only dotnet core implementation for it

**Comment by samuel-lucas6** [comment]
Good question. My issue is that this implementation isn't optimised and was written for learning purposes. Chances are the ChaCha8 implementation is still significantly slower than optimised ChaCha20 implementations. Additionally, I wouldn't recommend ChaCha8 or ChaCha12 because a) they're barely used/available (as you point out) and b) they unnecessarily reduce your security margin, with ChaCha8 being a bit close for comfort.

For these reasons, I think I would be doing a disservice by creating a NuGet. Instead, I would recommend [my libsodium binding](https://www.geralt.xyz/) or [Monocypher.NET](https://github.com/xoofx/Monocypher.NET) for ChaCha20. Both are [fast](https://monocypher.org/speed) libraries and will lead to better interoperability than using ChaCha8.
